### ISSUE TITLE
Custom Component update to homeassistant 2024.1.X Python dependencies not working because of home-assistant-bluetooth Python version

### ISSUE THREAD

**Issue by muhlba91** [home-assistant-libs/home-assistant-bluetooth#30]
I am the maintainer of the onyx custom component (https://github.com/muhlba91/onyx-homeassistant-integration) and wanted to update the version used by Poetry to `2024.1.x`.

However, it seems that from `2023.12.4` to `2024.1.x` some dependencies have changed as version solving fails because of `home-assistant-bluetooth` being required by `homeassistant`.

The error Poetry returns is:

```
The current project's supported Python range (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - home-assistant-bluetooth requires Python >=3.10,<3.13, so it will not be satisfied for Python >=3.13,<4.0

Because no versions of homeassistant match >2024.1.0,<2024.1.1 || >2024.1.1,<2024.1.2 || >2024.1.2,<2025.0.0
 and homeassistant (2024.1.1) depends on home-assistant-bluetooth (1.11.0), homeassistant (>2024.1.0,<2024.1.2 || >2024.1.2,<2025.0.0) requires home-assistant-bluetooth (1.11.0).
And because homeassistant (2024.1.0) depends on home-assistant-bluetooth (1.11.0)
 and homeassistant (2024.1.2) depends on home-assistant-bluetooth (1.11.0), homeassistant (>=2024.1.0,<2025.0.0) requires home-assistant-bluetooth (1.11.0).
So, because home-assistant-bluetooth (1.11.0) requires Python >=3.10,<3.13
 and onyx-homeassistant-integration depends on homeassistant (^2024.1.0), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For home-assistant-bluetooth, a possible solution would be to set the `python` property to ">=3.11,<3.13"
```

It looks like this update here causes the error https://github.com/home-assistant-libs/home-assistant-bluetooth/compare/v1.10.4...v1.11.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L29 which was released with `v1.11.0` and included in this year's homeassistant release.

**Comment by bdraco** [comment]
It looks like the publish workflow run on 3.10 so it failed to publish

I'll have to wait to fix this as we need to migrate to github trusted publishing on PyPI before we can get the new version out

https://github.com/home-assistant-libs/home-assistant-bluetooth/actions/runs/7464918240

**Comment by bdraco** [comment]
GitHub actions seems to be having trouble with windows runners.

I'll try again to do a release tomorrow https://github.com/Bluetooth-Devices/habluetooth/pull/25

**Comment by bdraco** [comment]
If https://github.com/home-assistant-libs/home-assistant-bluetooth/pull/35 successfully triggers a release, I'll bump this in HA and all the deps as well

**Comment by bdraco** [comment]
Looks like we are stuck on this one since PSR only supports python 3.10 and we need 3.11

https://github.com/python-semantic-release/python-semantic-release/blob/1d2bbdf23aab816cd9d6e26f537b5cec9e39dede/Dockerfile#L2C3-L2C3

**Comment by bdraco** [comment]
I asked a question at https://github.com/python-semantic-release/python-semantic-release/issues/801

Let's see if there is a solution.

**Comment by muhlba91** [comment]
thank you for providing the updates! i do hope there's a solution, as this blocks every custom integration using, at least, poetry from updating the home assistant version.

**Comment by bdraco** [comment]
0.12.0 published.  I'll get HA bumped shortly.

I had to fork PSR to make it work for 3.11+
